version: "2"
services:
    redis-master:
        image: 'redis:3.0-alpine'

    redis-sentinel:
        image: 'jvstein/redis-sentinel:latest'
        depends_on:
            - redis-master
        links:
            - redis-master

    postgres:
        image: 'postgres:9.6-alpine'
        environment:
            - POSTGRES_USER=pybossa
            - POSTGRES_PASSWORD=supersecretpassword
        volumes:
            - ./db_postgres:/var/lib/postgresql/data

    # initializes the database
    db-init:
        image: 'jvstein/pybossa:latest'
        depends_on:
            - postgres
        environment:
            - POSTGRES_URL=postgresql://pybossa:supersecretpassword@postgres/pybossa
        command: sh -c "sleep 5 && python cli.py db_create"

    # TODO: create a separate scheduler process??
    #       command: rqscheduler --host redis-master
    # background worker process
    pybossa-bgworker:
        image: 'gsipybossa:latest'
        build: .
        depends_on:
            - db-init
        environment:
            - POSTGRES_URL=postgresql://pybossa:supersecretpassword@postgres/pybossa
        command: python app_context_rqworker.py scheduled_jobs super high medium low email maintenance

    # web server
    pybossa:
        image: 'gsipybossa:latest'
        build: .
        container_name: pybossa

        depends_on:
            - db-init
        environment:
            - POSTGRES_URL=postgresql://pybossa:supersecretpassword@postgres/pybossa
        ports:
            - "8080:8080"