version: '2'
services:
    redis-master:
        image: 'redis:3.0-alpine'

    redis-sentinel:
        image: 'jvstein/redis-sentinel:latest'
        depends_on:
            - redis-master
        links:
            - redis-master

    postgres:
        image: 'postgres:9.6-alpine'
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./db_postgres:/var/lib/postgresql/data

    # initializes the database
    db-init:
        image: 'jvstein/pybossa:latest'
        depends_on:
            - postgres
        environment:
            - POSTGRES_URL=${POSTGRES_URL}
        command: sh -c "sleep 5 && python cli.py db_create"

    # TODO: create a separate scheduler process??
    #       command: rqscheduler --host redis-master
    # background worker process
    pybossa-bgworker:
        image: 'gsipybossa:latest'
        build: .
        depends_on:
            - db-init
        environment:
            - POSTGRES_URL=${POSTGRES_URL}
            - SECRET=${SECRET}
            - SECRET_KEY=${SECRET_KEY}
            - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
            - ITSDANGEROUSKEY=${ITSDANGEROUSKEY}
            - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
            - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - TASK_CSV_EXPORT_INFO_KEY=${TASK_CSV_EXPORT_INFO_KEY}
            - TASK_RUN_CSV_EXPORT_INFO_KEY=${TASK_RUN_CSV_EXPORT_INFO_KEY}
            - RESULT_CSV_EXPORT_INFO_KEY=${RESULT_CSV_EXPORT_INFO_KEY}
        command: python app_context_rqworker.py scheduled_jobs super high medium low email maintenance

    # web server
    pybossa:
        image: 'gsipybossa:latest'
        build: .
        container_name: pybossa
        env_file:
            - .env
        depends_on:
            - db-init
        environment:
            - POSTGRES_URL=${POSTGRES_URL}
            - SECRET=${SECRET}
            - SECRET_KEY=${SECRET_KEY}
            - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
            - ITSDANGEROUSKEY=${ITSDANGEROUSKEY}
            - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
            - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - TASK_CSV_EXPORT_INFO_KEY=${TASK_CSV_EXPORT_INFO_KEY}
            - TASK_RUN_CSV_EXPORT_INFO_KEY=${TASK_RUN_CSV_EXPORT_INFO_KEY}
            - RESULT_CSV_EXPORT_INFO_KEY=${RESULT_CSV_EXPORT_INFO_KEY}
        ports:
            - "8080:8080"